#!/bin/bash

umask 0002;

# PPI

# windmill 1 (ppi_nx85215) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/

# windmill 1 (ppi_nx85215) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/

# windmill 1 (ppi_nx85215) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/


# windmill 2 (ppi_nx85213) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/

# windmill 2 (ppi_nx85213) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/

# windmill 2 (ppi_nx85213) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/


# windmill 3 (ppi_nx85214) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/

# windmill 3 (ppi_nx85214) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/


# windmill 3 (ppi_nx85214) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_hr/




# RHI

# windmill 1 (ppi_nx85215) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/

# windmill 1 (ppi_nx85215) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/

# windmill 1 (ppi_nx85215) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM1 -p /users/jfigui/windmills_params/ppi_nx85215_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/


# windmill 2 (ppi_nx85213) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/

# windmill 2 (ppi_nx85213) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/

# windmill 2 (ppi_nx85213) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM2 -p /users/jfigui/windmills_params/ppi_nx85213_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/


# windmill 3 (ppi_nx85214) Speed greater than 0 wet
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori0_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori45_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori90_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori135_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori180_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori225_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori270_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedGT0.0_dBuZ_GE10.0.csv  -i span45_ori315_speedGT0_dBuZ_GE10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/

# windmill 3 (ppi_nx85214) Speed greater than 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedGT0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedGT0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/


# windmill 3 (ppi_nx85214) Speed = 0 dry
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori0.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori0_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori45.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori45_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori90.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori90_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori135.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori135_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori180.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori180_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori225.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori225_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori270.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori270_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/
python /users/jfigui/pyrad/src/pyrad_proc/scripts/main_process_data_windmills.py --windmill WM3 -p /users/jfigui/windmills_params/ppi_nx85214_span45.0_ori315.0_speedLE0.0_dBuZ_LT10.0.csv  -i span45_ori315_speedLE0_dBuZ_LT10 --radarbase /store/msrad/radar/pyrad_products/mals_sha_windmills_rhi/